language: c
matrix:
  include:
  - os: linux
    dist: focal
  - os: osx
  - os: windows
script:
- ./dps/travis-build.sh
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: "o902G6auBeNntyCtTuS4iIF4G+6vSOTh1DMo8BUe+C2JFp9gpu/divI/mQP5ujPIFakO0lMM52FhBoabqA76jiiZlcj5zuU6GytyGN9X2CPU3qycyU9K9XMpBY/kg6H74rD4jo4pXifodwO340gU9eQZcWn2cR3HTjlhC7B+e8Hv9YZZu7S3ahPZuPVdU0727JlEx6dhphVsQGw2g8c2TbNMBWcTIJImgbnug3pQXtkWUvHjnRTMVKNHiDw1eVlLCHLnZesxVWmIx3MeFp/5yrBuhMEx1kaFEgA1NY4qtT6P5hBLRh2WYbBEyqseeT3CekaRchB6Rz1cfvI/XRLMwCL/YSK0eCgwmuFCrjJ9fZS8d8rEYtat5EihbaGflAWFcudXNtWOE/nmctLW/adqALqStoAy6AIZU8yz3ltmv4Y0nsOIKuTim7Ayqm9QRKz9hmAdIYx3XV9y8v63tli7GtwFchYmkF7Xy5inf7tbX3RePke2YNKo4MP1v1TN5hzGZtSYcwdBrKBmEpIUU9d86XGzZx4O+8KE2pOVdsc4Ujp8RAbulKjHPM377dqayfOW4sYY3A4H+Y1gqHq5uMJQEK3RLeyTsN//GTiQv7mB6BYEurACsFSMo9EdO5xYZ6/oHbguZEdayB7Zfj+ac+CjeMVy9RqANGvAvZxBYgBiKKQ="
  file_glob: true
  file: dps/build/*.zip
  on:
    repo: kai4785/takp
    tags: true
  #draft: true
